try{
    console.log(a);
} catch(err){
    console.log("Error!!");
    console.log(err);
}